from PyQt5 import QtWidgets, QtCore, QtGui
class Tree:
    def __init__(self,centralwidget):
        self.tree = QtWidgets.QPushButton(centralwidget)
        self.tree.setGeometry(QtCore.QRect(400, 130, 211, 261))
        self.tree.setStyleSheet("background:transparent")
        self.tree.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../content/tree.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tree.setIcon(icon1)
        self.tree.setIconSize(QtCore.QSize(200, 200))
        self.tree.setObjectName("tree")
        self.tree_state = QtWidgets.QLabel(centralwidget)
        self.tree_state.adjustSize()
        self.tree_state.setText("Tree does not \nproduce oxygen")
        self.tree_state.setGeometry(QtCore.QRect(430, 110, 200, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setItalic(True)
        self.tree_state.setFont(font)
        self.tree_state.setObjectName("tree_state")